from user import User
from admin import Admin
user_0=Admin('刘','方炎',23,'男')
user_0.describe_user()
user_0.privileges.show_privileges()
user_1=User('刘','方炎',23,'男')
user_1.describe_user()
user_1.increment_login_attempts()
user_1.increment_login_attempts()
user_1.increment_login_attempts()
print(user_1.login_attempts)
user_1.reset_login_attempts()
print(user_1.login_attempts)
user_1.get_user()
user_2=User('单','建昌',22,'男')
user_2.describe_user()
user_2.get_user()
user_3=User('席','笑文',21,'女')
user_3.describe_user()
user_3.get_user()